server:
  port: 9002

nacos:
  discovery:
    server-addr: 124.220.192.22:8848

dubbo:
  application:
    name: baas-task
    qosEnable: true
    qosPort: 22223
    qosAcceptForeignIp: false
  protocol:
    name: dubbo
    port: 20884
  registry:
    address: nacos://124.220.192.22:8848
